name: hipages CI/CD

on:
  push:
    branches:
      - master
      - release
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - release
    types: [opened, synchronize]
env:
  REGISTRY_URL: ghcr.io

jobs:
  image:
    # build and scan docker image
    runs-on: ubuntu-latest
    name: Build container image ğŸ—ï¸
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: hipagesgroup/actions/checkout@master

      - uses: hipagesgroup/actions/build-scan-publish-container@master
        id: container
        with:
          registry: ghcr
          registry_url: ${{ env.REGISTRY_URL }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          npm-token: ${{ secrets.HIP_CI_GHCR }}
